using System;
using System.Collections.Generic;
using System.Text;
using Dapper.Contrib.Extensions;

namespace TStack.Dapper.Extensions
{
    /// <summary>
    /// Specify the destination table name mapped to the entity.
    /// </summary>
    public class TableNameAttribute : TableAttribute
    {
        public TableNameAttribute(string tableName) : base(tableName)
        {
        }
    }
    /// <summary>
    /// Specify the property as a key that is automatically generated by the database.
    /// </summary>
    public class PrimaryAttribute : KeyAttribute
    {

    }
    /// <summary>
    /// Specify the property as a key explicitly which is not automatically generated by the database.
    /// </summary>
    public class ExplicitPrimaryAttribute : ExplicitKeyAttribute
    {

    }
    /// <summary>
    /// Specify the property that should be excluded from an update.
    /// </summary>
    public class ExcludedAttribute : ComputedAttribute
    {

    }
    /// <summary>
    /// Specify the property if it is writable or not.
    /// </summary>
    public class SaltAttribute : WriteAttribute
    {
        public SaltAttribute(bool write) : base(write)
        {
        }
    }
}
